operatorImageName: lightbend/sparkoperator
operatorVersion: 1.3.0-M1-OpenJDK-2.4.4-0.8.2-cloudflow-2.12
imagePullPolicy: IfNotPresent
sparkJobNamespace: default

rbac:
  create: true

serviceAccounts:
  spark:
    create: true
    name:
  sparkoperator:
    create: true
    name:

enableWebhook: true
enableMetrics: true

controllerThreads: 10
ingressUrlFormat: ""
installCrds: true
metricsPort: 10254
metricsEndpoint: "/metrics"
metricsPrefix: ""
resyncInterval: 30
webhookPort: 8080

## Node labels for pod assignment
## Ref: https://kubernetes.io/docs/user-guide/node-selection/
##
nodeSelector: {}

logLevel: 2
